version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      # Group Rails updates so you don't get 10 PRs at once
      rails:
        patterns:
          - "rails"
          - "action*"
          - "active*"
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"