default: &default
  adapter: postgresql
  encoding: unicode
  gssencmode: disable
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", "5433") %>
  username: <%= ENV.fetch("DB_USER", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "password") %>

development:
  primary:
    <<: *default
    database: nybenchmark_app_development

  queue:
    <<: *default
    database: nybenchmark_app_development_queue
    migrations_paths: db/queue_migrate

  cache:
    <<: *default
    database: nybenchmark_app_development_cache
    migrations_paths: db/cache_migrate

  cable:
    <<: *default
    database: nybenchmark_app_development_cable
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *default
    database: nybenchmark_app_test

  queue:
    <<: *default
    database: nybenchmark_app_test_queue
    migrations_paths: db/queue_migrate

  cache:
    <<: *default
    database: nybenchmark_app_test_cache
    migrations_paths: db/cache_migrate

  cable:
    <<: *default
    database: nybenchmark_app_test_cable
    migrations_paths: db/cable_migrate

production:
  primary:
    <<: *default
    database: <%= ENV["POSTGRES_DB"] || ENV["DB_NAME"] || "nybenchmark_app_production" %>
    host: <%= ENV["POSTGRES_HOST"] || ENV["DB_HOST"] || "localhost" %>
    port: <%= ENV.fetch("POSTGRES_PORT", ENV.fetch("DB_PORT", "5432")) %>
    username: <%= ENV["POSTGRES_USER"] || ENV["DB_USER"] || "postgres" %>
    password: <%= ENV["POSTGRES_PASSWORD"] || ENV["DB_PASSWORD"] || "" %>

  queue:
    <<: *default
    database: <%= ENV["POSTGRES_DB"] || ENV["DB_NAME"] || "nybenchmark_app_production" %>
    host: <%= ENV["POSTGRES_HOST"] || ENV["DB_HOST"] || "localhost" %>
    port: <%= ENV.fetch("POSTGRES_PORT", ENV.fetch("DB_PORT", "5432")) %>
    username: <%= ENV["POSTGRES_USER"] || ENV["DB_USER"] || "postgres" %>
    password: <%= ENV["POSTGRES_PASSWORD"] || ENV["DB_PASSWORD"] || "" %>
    migrations_paths: db/queue_migrate

  cache:
    <<: *default
    database: <%= ENV["POSTGRES_DB"] || ENV["DB_NAME"] || "nybenchmark_app_production" %>
    host: <%= ENV["POSTGRES_HOST"] || ENV["DB_HOST"] || "localhost" %>
    port: <%= ENV.fetch("POSTGRES_PORT", ENV.fetch("DB_PORT", "5432")) %>
    username: <%= ENV["POSTGRES_USER"] || ENV["DB_USER"] || "postgres" %>
    password: <%= ENV["POSTGRES_PASSWORD"] || ENV["DB_PASSWORD"] || "" %>
    migrations_paths: db/cache_migrate

  cable:
    <<: *default
    database: <%= ENV["POSTGRES_DB"] || ENV["DB_NAME"] || "nybenchmark_app_production" %>
    host: <%= ENV["POSTGRES_HOST"] || ENV["DB_HOST"] || "localhost" %>
    port: <%= ENV.fetch("POSTGRES_PORT", ENV.fetch("DB_PORT", "5432")) %>
    username: <%= ENV["POSTGRES_USER"] || ENV["DB_USER"] || "postgres" %>
    password: <%= ENV["POSTGRES_PASSWORD"] || ENV["DB_PASSWORD"] || "" %>
    migrations_paths: db/cable_migrate